# Example configuraton for Fedora Messaging

# Broker address
amqp_url = "amqp://"

# # Authentication is TLS-based
# [tls]
# ca_cert = "/etc/pki/tls/certs/ca-bundle.crt"
# keyfile = "/my/client/key.pem"
# certfile = "/my/client/cert.pem"

[consumer_config]
    fasjson_url = "https://fasjson.tinystage.test"

    [consumer_config.stomp]
    # Broker URI
    # http://nikipore.github.io/stompest/protocol.html#stompest.protocol.failover.StompFailoverUri
    # Example: failover:(tcp://remote1:61615,tcp://localhost:61616)?randomize=false,startupMaxReconnectAttempts=3,initialReconnectDelay=7,maxReconnectDelay=8,maxReconnectAttempts=0
    uri = "tcp://localhost:61613"

    # Virtual Host
    vhost = "/"

    # Authentication
    user = "guest"
    pass = "guest"

    # Queue to subscribe to
    queue = "/queue/fedora_from_esb"

    # Heartbeat to keep the connection open
    heartbeat = 1000

    # How many messages to prefetch
    prefetch_size = 100

    [consumer_config.bugzilla]
    # Products to relay messages for - messages for bugs files against
    # other products will be ignored
    products = ["Fedora", "Fedora EPEL"]
    # Whether to modify messages to look more like Bugzilla 4 ones did
    bz4compat = true


[client_properties]
app = "bugzilla2fedmsg"

[log_config]
version = 1
disable_existing_loggers = true

[log_config.formatters.simple]
format = "[%(name)s %(levelname)s] %(message)s"

[log_config.handlers.console]
class = "logging.StreamHandler"
formatter = "simple"
stream = "ext://sys.stdout"

[log_config.loggers.fedora_messaging]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.loggers.bugzilla2fedmsg]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.root]
level = "WARNING"
handlers = ["console"]
